from spanish_audio_20260912.review import patch
patch(15350693,{
1:({'qMdFootnote':'I asked her to answer my question.','aMdFootnote':'Le pedí que respondiera mi pregunta.'},'Clarify who is answering.'),
19:({'qMdFootnote':'The rainy season starts now.','aMdFootnote':'La temporada de lluvias empieza ahora.'},'Use temporada, not a calendar season estación.'),
20:({'qMdFootnote':'The party was full of fun.','aMdFootnote':'La fiesta estuvo llena de diversión.'},'Use noun diversión.'),
47:({'aMdFootnote':'Alteza, los invitados esperan.'},'Correct direct royal address.'),
72:({'aMdFootnote':'Pasa la página para seguir leyendo.'},'Turn a page is pasar, not girar.'),
75:({'qMdFootnote':'The table is firm.','aMdFootnote':'La mesa está firme.'},'Use the adjective naturally.'),
87:({'qMdFootnote':'It is a social problem.','aMdFootnote':'Es un problema social.'},'Social does not mean sociable in this context.'),
89:({'qMdFootnote':'He became the champion of the tournament.','aMdFootnote':'Se convirtió en el campeón del torneo.'},'Champion applies to a tournament, not one match.'),
90:({'qMdFootnote':'The car is for sale today.'},'En venta means for sale, not discounted.'),
99:({'qMdBody':'to tell it to him or her','qMdFootnote':'I need to tell it to him tomorrow.'},'Decírselo includes both indirect recipient and direct object.'),
119:({'qMdFootnote':"He doesn't want me to think about it."},'Align unrelated examples.'),
121:({'aMdFootnote':'Ella se miró en el espejo.'},'Natural reflexive mirror construction.'),
125:({'qMdFootnote':'They have discovered an ancient city.','aMdFootnote':'Han descubierto una ciudad antigua.'},'Use target descubierto.'),
177:({'qMdFootnote':'The fabric is soft and smooth.','aMdFootnote':'La tela es suave.'},'Avoid false-friend smooth for a charming person.'),
184:({'qMdFootnote':'You all know the answer.','aMdFootnote':'Todos sabéis la respuesta.'},'Use saber naturally rather than a discourse-marker calque.'),
185:({'aMdFootnote':'Se quitó la vida el año pasado.','qMdFootnote':'His death was ruled a suicide.','aMdFootnote':'Su muerte fue considerada un suicidio.'},'Use noun suicidio.'),
202:({'qMdFootnote':'The fire destroyed the house.','aMdFootnote':'El incendio destruyó la casa.'},'Use noun incendio.'),
208:({'qMdFootnote':'Transport is expensive here.','aMdFootnote':'El transporte es caro aquí.'},'Use noun transporte, not verb transportar.'),
222:({'qMdFootnote':'I need one particular book.','aMdFootnote':'Necesito un libro en particular.'},'Avoid false-friend particular for fussy.'),
226:({'qMdFootnote':'That is a bad excuse.','aMdFootnote':'Esa es una mala excusa.'},'Use noun excusa.'),
228:({'qMdFootnote':'She is a curious child.','aMdFootnote':'Es una niña curiosa.'},'Avoid unnatural estar curiosa sobre.'),
269:({'qMdFootnote':'We left at dawn.','aMdFootnote':'Salimos al amanecer.'},'Use noun amanecer.'),
284:({'qMdBody':'favorite (feminine)','qMdFootnote':'This is my favorite song.','aMdFootnote':'Esta es mi canción favorita.'},'Demonstrate the feminine target form.'),
291:({'qMdFootnote':'I need to buy gasoline.','aMdFootnote':'Necesito comprar gasolina.'},'Replace awkward refill my car calque.'),
300:({'aMdFootnote':'Ella es la clara ganadora.'},'Natural adjective placement.'),
312:({'aMdFootnote':'Emitiré mi voto mañana.'},'Use noun voto.'),
327:({'qMdFootnote':'He works in civil aviation.','aMdFootnote':'Trabaja en la aviación civil.'},'Civil does not mean polite in this context.'),
334:({'aMdFootnote':'Debo admitir que tenías razón.'},'Add required conjunction.'),
381:({'qMdFootnote':'She adds salt to the food.'},'Correct English preposition.'),
390:({'qMdFootnote':'Help!'},'Remove Spanish opening exclamation mark from English.'),
399:({'qMdFootnote':'She has bought a new car.','aMdFootnote':'Ella ha comprado un coche nuevo.'},'Avoid perfect tense with a completed ayer period.'),
405:({'qMdFootnote':'Pass the ball.'},'Match ustedes command, not nosotros suggestion.'),
410:({'qMdBody':'I seem','qMdFootnote':'I seem tired today.','aMdFootnote':'Parezco cansado hoy.'},'Parezco and me parezco have different constructions.'),
435:({'qMdFootnote':'He fulfilled his task.'},'Align unrelated example sentences.'),
444:({'qMdFootnote':'The cause is unknown.','aMdFootnote':'La causa es desconocida.'},'Replace unnatural llamante example.'),
450:({'qMdFootnote':'The police are investigating the crime.','aMdFootnote':'La policía investiga el delito.'},'Use singular count noun delito naturally.'),
498:({'qMdFootnote':"I'll send you the document via email."},'Match email, not fax.')})
