from spanish_audio_20260912.review import patch
patch(15350690,{
8:({'qMdBody':'were, was (subjunctive)'},'Clarify the imperfect subjunctive.'),
10:({'aMdFootnote':'Él ha cambiado, ya no es el mismo.'},'Not the same differs from not himself.'),
21:({'aMdFootnote':'El encuentro fue inesperadamente agradable.'},'Use target encuentro and natural phrasing.'),
23:({'qMdFootnote':'The dance starts at eight.','aMdFootnote':'El baile empieza a las ocho.'},'Use the noun baile, not the verb bailar.'),
35:({'qMdBody':'reason, the why'},'Porqué is a noun, not the question word por qué.'),
69:({'qMdFootnote':'I want to learn Spanish.','aMdFootnote':'Quiero aprender español.'},'Fluently describes speaking, not learning.'),
82:({'qMdFootnote':'Please do not touch the glass.','aMdFootnote':'Por favor, no toques el vidrio.'},'Example must use the taught touch sense.'),
85:({'qMdFootnote':'The entry is on the left.','aMdFootnote':'La entrada está a la izquierda.'},'Replace unnatural invitadora.'),
96:({'qMdFootnote':'This book is his.','aMdFootnote':'Este libro es suyo.'},'Use target suyo, not su.'),
99:({'qMdFootnote':'He received a hard hit.','aMdFootnote':'Recibió un golpe fuerte.'},'Use the noun golpe.'),
104:({'qMdFootnote':"We'll begin the walk through the mountains."},'Match montaña rather than forest.'),
123:({'qMdFootnote':'Daddy bought me a new bike.'},'Use target daddy.'),
131:({'qMdFootnote':'I want to try again.','aMdFootnote':'Quiero intentar de nuevo.'},'Use intentar, not probar.'),
135:({'aMdBody':'me refiero','qMdFootnote':'I refer to that document.','aMdFootnote':'Me refiero a ese documento.'},'Refer to requires reflexive referirse.'),
136:({'qMdFootnote':'You have all done it well.','aMdFootnote':'Todos lo habéis hecho bien.'},'Complete hacer with the needed object; remove editorial speech text.'),
137:({'aMdFootnote':'Pelearán por la justicia.'},'Use target pelear.'),
150:({'qMdFootnote':'The couple danced beautifully.','aMdFootnote':'La pareja bailó muy bien.'},'Remove singular/plural agreement problem.'),
154:({'qMdFootnote':'She has taken my book.','aMdFootnote':'Ella ha tomado mi libro.'},'Avoid unnatural tomado for an occupied seat.'),
176:({'qMdFootnote':'Did you ask where he lives?','aMdFootnote':'¿Preguntaste dónde vive?'},'Ask for help requires pedir; use a question with preguntar.'),
199:({'qMdFootnote':'They have been married for a year.','aMdFootnote':'Llevan un año casados.'},'Use adjective casado, not only the verb casarse.'),
226:({'qMdBody':'to have ... you (auxiliary)','qMdFootnote':"I'm glad to have met you.",'aMdFootnote':'Me alegra haberte conocido.'},'Haberte is an auxiliary with a clitic, not possession tenerte.'),
307:({'qMdFootnote':'I have received your letter.','aMdFootnote':'He recibido tu carta.'},'Use target participle recibido.'),
310:({'qMdFootnote':"I'll call you directly.",'aMdFootnote':'Te llamaré directamente.'},'Use directly for direct contact, not immediately after.'),
316:({'aMdFootnote':'Los militares protegen las fronteras del país.'},'Use target militar rather than soldado.'),
343:({'qMdFootnote':'She is younger than her sister.','aMdFootnote':'Ella es menor que su hermana.'},'Menor describes age, not youthful appearance.'),
394:({'qMdFootnote':'Breakfast is at seven.','aMdFootnote':'El desayuno es a las siete.'},'Use noun desayuno.'),
401:({'qMdFootnote':'Something strange has occurred.','aMdFootnote':'Ha ocurrido algo extraño.'},'Use target participle ocurrido.'),
408:({'qMdFootnote':'We heard a shot.','aMdFootnote':'Oímos un disparo.'},'Avoid ambiguous idiom shot in the dark and unnatural dar un disparo.'),
421:({'aMdFootnote':'Continuemos nuestro viaje mañana.'},'Use target continuar.'),
423:({'aMdFootnote':'Nos vemos en la esquina de la calle.'},'Translate meeting arrangement naturally.'),
427:({'qMdFootnote':'It was a grand celebration.','aMdFootnote':'Fue una celebración grandiosa.'},'Match grand with grandioso in context.'),
443:({'qMdFootnote':'The child remained still.','aMdFootnote':'El niño se quedó quieto.'},'Use quieto for a motionless person rather than a room.')})
