from review import save
save('15260285',{
56:('admission','допуск','Admission to the room requires permission.','Допуск в комнату требует разрешения.'),
91:('inventory','опись','We made an inventory of the books.','Мы составили опись книг.'),
97:('to cut in','вмешаться','He tried to cut in while I was speaking.','Он пытался вмешаться, пока я говорил.'),
143:('hustle','суета','I dislike the hustle of the city.','Мне не нравится городская суета.'),
146:('overestimate','переоценить','He overestimated his strength.','Он переоценил свои силы.'),
218:('machine gunner','пулемётчик','The machine gunner took his place.','Пулемётчик занял своё место.'),
226:('Isabella','Изабелла','Isabella is a name.','Изабелла — имя.'),
234:('Kaluga','Калуга','I visited Kaluga last summer.','Я посетил Калугу прошлым летом.'),
254:('kvass','квас','I made kvass last summer.','Я сделал квас прошлым летом.'),
273:('annotation','примечание','I read the annotation.','Я прочитал примечание.'),
287:('pull up','подтянуться','He pulled himself up onto the wall.','Он подтянулся на стену.'),
297:('to be broadcast','транслироваться','The game will be broadcast live.','Игра будет транслироваться в прямом эфире.'),
313:('gathering','сборище','A noisy gathering stood by the house.','Шумное сборище стояло у дома.'),
319:('to decline','спадать','Demand began to decline.','Спрос начал спадать.'),
385:('self-confident','уверенный в себе','She is very self-confident.','Она очень уверена в себе.'),
396:('little finger','мизинец','He hurt his little finger.','Он повредил мизинец.'),
409:('agony','мучение','He was in agony.','Он испытывал мучения.'),
438:('Aeroflot','Аэрофлот','Aeroflot is a big airline.','Аэрофлот — большая авиакомпания.'),
449:('adept','знаток','He is an adept in this art.','Он знаток этого искусства.'),
485:('full-time','полный рабочий день','She works full-time.','Она работает полный рабочий день.'),
499:('to smear','мазать','I smear butter on bread.','Я мажу масло на хлеб.'),
})
