from review import save
save('15260268',{
15:('intercept','перехватить','The spy will intercept the letter.','Шпион перехватит письмо.'),
36:('madly','безумно','She was madly in love with him.','Она была безумно влюблена в него.'),
66:('to dispose','распорядиться','He can dispose of his property freely.','Он может свободно распорядиться своей собственностью.'),
80:('inspiration','вдохновение','Music gives him inspiration.','Музыка даёт ему вдохновение.'),
103:('individuality','индивидуальность','She values her individuality.','Она ценит свою индивидуальность.'),
112:('chase','погоня','The chase lasted an hour.','Погоня длилась час.'),
132:('mechanics','механика','He loves mechanics.','Он любит механику.'),
143:('adapt','приспособить','We will adapt the room for work.','Мы приспособим комнату для работы.'),
164:('ecology','экология','He loves ecology.','Он любит экологию.'),
165:('ethical','этический','This is an ethical question.','Это этический вопрос.'),
167:('rail','рельс','The train is on the rails.','Поезд стоит на рельсах.'),
179:('floodplain','пойма','The village is on the floodplain.','Деревня стоит в пойме.'),
199:('waste','отходы','This is industrial waste.','Это промышленные отходы.'),
200:('greatcoat','шинель','He wore a greatcoat.','Он носил шинель.'),
206:('to get angry','злиться','He is getting angry.','Он злится.'),
207:('to crash','разбиться','The car crashed.','Машина разбилась.'),
228:('to sit out','пропустить','He had to sit out the game.','Ему пришлось пропустить игру.'),
238:('sociology','социология','He loves sociology.','Он любит социологию.'),
239:('pirate','пират','The pirate has a box of gold.','У пирата есть ящик с золотом.'),
242:('to reduce','сократить','We will reduce the list.','Мы сократим список.'),
254:('reproduction','воспроизведение','The reproduction of this image is clear.','Воспроизведение этого изображения чёткое.'),
258:('annoyance','досада','He felt annoyance at his error.','Он чувствовал досаду из-за своей ошибки.'),
261:('repression','репрессия','Many people suffered from repression.','Многие люди пострадали от репрессий.'),
282:('considerably','изрядно','He has grown considerably.','Он изрядно вырос.'),
293:('wrestler','борец','The wrestler won the fight.','Борец выиграл бой.'),
302:('exceed','превысить','Our costs exceeded our income.','Наши расходы превысили наш доход.'),
315:('sympathize','сочувствовать','I sympathize with you.','Я сочувствую вам.'),
317:('doom','обречь','This will doom him to failure.','Это обречёт его на неудачу.'),
368:('mineral','минеральный','I bought mineral water.','Я купил минеральную воду.'),
381:('I bet','небось','I bet he is already here.','Небось он уже здесь.'),
394:('henceforth','впредь','Henceforth, please lock the door.','Впредь, пожалуйста, запирайте дверь.'),
400:('rector','ректор','The rector announced a new policy.','Ректор объявил о новой политике.'),
408:('deliberately','намеренно','He deliberately gave a false answer.','Он намеренно дал ложный ответ.'),
419:('seat','сиденье','The seat is old.','Сиденье старое.'),
446:('to look out','выглянуть','He wanted to look out of the window.','Он хотел выглянуть из окна.'),
466:('righteousness','праведность','They believed in his righteousness.','Они верили в его праведность.'),
})
