from review import save
save('15260283',{
34:('abundantly','обильно','She watered the flowers abundantly.','Она обильно полила цветы.'),
40:('palms','ладони','She pressed her palms together.','Она прижала ладони друг к другу.'),
79:('trigger','спусковой крючок','He pulled the trigger.','Он нажал на спусковой крючок.'),
106:('to be bought','быть купленным','The house is to be bought tomorrow.','Дом должен быть куплен завтра.'),
107:('to be lucky','посчастливиться','I was lucky to meet her.','Мне посчастливилось встретить её.'),
110:('boiler room','котельная','It is hot in the boiler room.','В котельной жарко.'),
113:('urinary','мочевой','This is the urinary bladder.','Это мочевой пузырь.'),
128:('hertz','герц','The frequency is one hundred hertz.','Частота — сто герц.'),
181:('rocky','скалистый','The coast is rocky.','Берег скалистый.'),
191:('lightly','легонько','She lightly touched his hand.','Она легонько коснулась его руки.'),
204:('remembrance','память','We keep this in remembrance of her.','Мы храним это в память о ней.'),
206:('scepter','скипетр','The king held a scepter.','Король держал скипетр.'),
224:('lively','бойкий','She is a lively girl.','Она бойкая девочка.'),
232:('picket','пикет','Workers organized a picket.','Рабочие организовали пикет.'),
239:('novelist','романист','He is a famous novelist.','Он известный романист.'),
289:('Astrakhan','Астрахань','He lives in Astrakhan.','Он живёт в Астрахани.'),
301:('to have sex','заниматься сексом','They like to have sex at night.','Они любят заниматься сексом ночью.'),
308:("old women's",'старушечий',"I hear old women's voices.",'Я слышу старушечьи голоса.'),
377:('bristle','щетина','The brush has hard bristles.','У щётки жёсткая щетина.'),
390:('caste','каста','They belong to the same caste.','Они принадлежат к одной касте.'),
402:('one-time','разовый','This is a one-time payment.','Это разовый платёж.'),
411:('louse','вошь','A louse crawled on my arm.','Вошь ползла по моей руке.'),
436:('tan','загар','She has a dark tan.','У неё тёмный загар.'),
438:('Dzerzhinsky','Дзержинский','Dzerzhinsky is mentioned in the book.','Дзержинский упоминается в книге.'),
454:('extermination','истребление','The extermination of rats began.','Началось истребление крыс.'),
457:('X-ray','рентгеновский','I need an X-ray image of my arm.','Мне нужен рентгеновский снимок руки.'),
460:('classify','классифицировать','They classify books by subject.','Они классифицируют книги по теме.'),
468:('Bryansk','Брянск','He lives in Bryansk.','Он живёт в Брянске.'),
475:('cobblestone','булыжник','There is a cobblestone on the street.','На улице лежит булыжник.'),
})
