from review import save
save('15260281',{
28:('to spread apart','раздвинуть','He spread his fingers apart.','Он раздвинул пальцы.'),
56:('freebie','халява','I got this shirt as a freebie.','Я получил эту рубашку на халяву.'),
69:('shackle','приковать','They shackled him to the wall.','Они приковали его к стене.'),
84:('elective','выборный','This is an elective council.','Это выборный совет.'),
107:('guild','гильдия',"He joined the writers’ guild.",'Он вступил в гильдию писателей.'),
129:('nominal','номинальный','This is the nominal price.','Это номинальная цена.'),
130:('inhuman','бесчеловечный','Their treatment of prisoners was inhuman.','Их обращение с заключёнными было бесчеловечным.'),
140:("Lord's",'господень',"This is the Lord's will.",'Это воля Господня.'),
144:('activate','активировать','We must activate the system.','Мы должны активировать систему.'),
158:('individually','индивидуально','The teacher works with them individually.','Учитель работает с ними индивидуально.'),
160:('overnight stay','ночлег','We found a place for an overnight stay.','Мы нашли место для ночлега.'),
168:('pinch','ущипнуть','She pinched my hand.','Она ущипнула меня за руку.'),
169:('sweep','пронестись','A storm swept through the city.','Буря пронеслась по городу.'),
174:('urn','урна','The urn contains his ashes.','Урна содержит его прах.'),
190:('alloy','сплав','This metal is an alloy.','Этот металл — сплав.'),
214:('strand','прядь','A strand of hair fell over her face.','Прядь волос упала ей на лицо.'),
249:('to torture','пытать','They tortured him.','Они пытали его.'),
267:('abroad','за границей','She works abroad.','Она работает за границей.'),
289:('speculation','предположение','This is only speculation.','Это только предположение.'),
293:('agriculture','сельское хозяйство','He works in agriculture.','Он работает в сельском хозяйстве.'),
294:('Hermitage','Эрмитаж','We were at the Hermitage.','Мы были в Эрмитаже.'),
312:('cubic','кубический','We need ten cubic meters of water.','Нам нужно десять кубических метров воды.'),
338:('loader','грузчик','The loader lifted the heavy box.','Грузчик поднял тяжёлый ящик.'),
454:('coursework','учебные задания','I finished my coursework yesterday.','Я закончил свои учебные задания вчера.'),
460:('demarcation','разграничение','The demarcation of powers is clear.','Разграничение полномочий ясно.'),
462:('glare','ослепительный свет','The glare hurt my eyes.','От ослепительного света у меня болели глаза.'),
485:('Omsk','Омск','I visited Omsk last summer.','Я посетил Омск прошлым летом.'),
})
