from review import save
save('15260251',{
14:('forgive','простить','Please forgive my error.','Пожалуйста, простите мою ошибку.'),
25:('to fulfill','выполнить','We must fulfill these requirements.','Мы должны выполнить эти требования.'),
34:('stream','поток','The stream of people never stopped.','Поток людей никогда не останавливался.'),
41:('something','нечто','I saw something strange.','Я видел нечто странное.'),
61:('to define','определять','How do you define this concept?','Как вы определяете это понятие?'),
86:('horror','ужас','She looked at him in horror.','Она смотрела на него в ужасе.'),
99:('loss','потеря','His death was a great loss.','Его смерть была большой потерей.'),
115:('to sound','звучать','His voice sounds strange.','Его голос звучит странно.'),
118:('appearance','внешность','Her appearance changed.','Её внешность изменилась.'),
124:('rarely','редко','She rarely comes home.','Она редко приходит домой.'),
127:('honor','честь','It is an honor to work with you.','Для меня честь работать с вами.'),
157:('commit','совершить','He did not commit a crime.','Он не совершил преступления.'),
163:('spring','весна','Spring has begun.','Весна началась.'),
168:('get','достать',"I will get the book from my room.",'Я достану книгу из своей комнаты.'),
191:('to learn','научиться','I want to learn to read.','Я хочу научиться читать.'),
199:('reduction','снижение','There was a reduction in prices.','Произошло снижение цен.'),
207:('to ride','ездить','I ride to work in a car.','Я езжу на работу на машине.'),
215:('exhibition','выставка','The exhibition of pictures opens tomorrow.','Выставка картин открывается завтра.'),
237:('perspective','точка зрения','I understand your perspective.','Я понимаю вашу точку зрения.'),
257:("let's say",'скажем',"Come in the morning, let's say at ten.",'Приходите утром, скажем, в десять.'),
272:('true','истинный','I know the true reason.','Я знаю истинную причину.'),
277:('artistic','художественный','She has artistic ability.','У неё есть художественные способности.'),
285:('marriage','брак','They have a happy marriage.','У них счастливый брак.'),
330:('noise','шум','I heard noise in the street.','Я слышал шум на улице.'),
374:('expectation','ожидание','His expectations were high.','Его ожидания были высокими.'),
387:('from there','оттуда','He came from there.','Он пришёл оттуда.'),
394:('autumn','осень','Autumn has begun.','Осень началась.'),
422:('to give back','отдавать','I am giving him back his book.','Я отдаю ему его книгу.'),
456:('worthy','достойный','He is worthy of respect.','Он достоин уважения.'),
})
