from review import save
save('15260287',{
10:('most holy','пресвятой','They prayed to the Most Holy Virgin.','Они молились Пресвятой Деве.'),
18:('Internationale','Интернационал','They sing the Internationale.','Они поют «Интернационал».'),
28:('cloudiness','облачность','Cloudiness increased during the day.','Облачность увеличилась за день.'),
29:('atrocity','зверство','They committed an atrocity.','Они совершили зверство.'),
39:('entropy','энтропия','The entropy increased.','Энтропия увеличилась.'),
44:('provocative','провокационный','He asked a provocative question.','Он задал провокационный вопрос.'),
71:('junction','узловая станция','The train stopped at the junction.','Поезд остановился на узловой станции.'),
76:('hang out','тусоваться','They hang out here.','Они тусуются здесь.'),
88:('collectivization','коллективизация','He wrote about collectivization.','Он писал о коллективизации.'),
90:('bony','костистый','The fish was too bony.','Рыба была слишком костистой.'),
96:('womb','утроба','The child grows in the womb.','Ребёнок растёт в утробе.'),
97:('Albanian','албанский','He knows the Albanian language.','Он знает албанский язык.'),
112:('magnanimous','великодушный','He was magnanimous toward his enemy.','Он был великодушен к своему врагу.'),
189:('confiscation','конфискация','The court ordered the confiscation of his property.','Суд постановил провести конфискацию его имущества.'),
219:('categorical','категорический','He gave a categorical refusal.','Он дал категорический отказ.'),
221:('ubiquitous','повсеместный','The use of this word is ubiquitous.','Употребление этого слова повсеместно.'),
239:('compote','фруктовый десерт','She made an apple compote.','Она приготовила фруктовый десерт из яблок.'),
285:('gallop','галоп','The horse moved at a gallop.','Лошадь двигалась галопом.'),
329:('Talmud','Талмуд','He reads the Talmud.','Он читает Талмуд.'),
335:('closet','стенной шкаф','My coat is in the closet.','Моё пальто в стенном шкафу.'),
336:('Portuguese','португальский','I study the Portuguese language.','Я изучаю португальский язык.'),
344:('verification','проверка','This information needs verification.','Эта информация требует проверки.'),
386:('Aquarius','Водолей','He was born under Aquarius.','Он родился под знаком Водолея.'),
406:('above all','прежде всего','Above all, we need peace.','Прежде всего, нам нужен мир.'),
411:('unbridled','безудержный','They felt unbridled joy.','Они чувствовали безудержную радость.'),
434:('Capricorn','Козерог','My zodiac sign is Capricorn.','Мой знак зодиака — Козерог.'),
435:('locker room','раздевалка','The locker room was crowded.','Раздевалка была переполнена.'),
437:('piracy','пиратство','Piracy is a danger at sea.','Пиратство — опасность на море.'),
446:('relay','эстафета','They won the relay race.','Они победили в эстафете.'),
452:('sneaker','кроссовок','I bought a new pair of sneakers.','Я купил новую пару кроссовок.'),
464:('industrialization','индустриализация','Industrialization changed the country.','Индустриализация изменила страну.'),
467:('ocular','глазной','He has an ocular disease.','У него глазная болезнь.'),
484:('monumental','монументальный','This is a monumental building.','Это монументальное здание.'),
})
# Genitive plural of masculine кроссовок.
save('15260287',{452:('sneaker','кроссовок','I bought a new pair of sneakers.','Я купил новую пару кроссовок.')})
